# =========================================================
# Auth Service Configuration (Local Development)
# Environment variables will override these values
# =========================================================

[server]
host = "${SERVER_HOST:0.0.0.0}"
port = "${HTTP_PORT:8001}"
read_timeout = "30s"
write_timeout = "30s"
idle_timeout = "120s"
shutdown_timeout = "30s"

[database]
host = "${AUTH_DB_HOST:localhost}"
port = "${AUTH_DB_PORT:5432}"
name = "${AUTH_DB_NAME:auth_db}"
user = "${AUTH_DB_USER:postgres}"
password = "${AUTH_DB_PASSWORD:testpassword}"
ssl_mode = "${AUTH_DB_SSL_MODE:disable}"
max_open_conns = 25
max_idle_conns = 10
conn_max_lifetime = "1h"
migration_path = "migrations"

[redis]
url = "${REDIS_URL:redis://localhost:6379}"
password = "${REDIS_PASSWORD:}"
db = 0
max_retries = 3
pool_size = 10
min_idle_conns = 2
dial_timeout = "5s"
read_timeout = "3s"
write_timeout = "3s"
pool_timeout = "4s"
idle_timeout = "300s"

[jwt]
access_secret = "${JWT_ACCESS_SECRET:dev-access-secret-key-minimum-32-characters-long}"
refresh_secret = "${JWT_REFRESH_SECRET:dev-refresh-secret-key-minimum-32-characters-long}"
issuer = "${JWT_ISSUER:auth-service}"
access_expiry = "15m"
refresh_expiry = "168h"
algorithm = "${JWT_ALGORITHM:HS256}"

[security]
bcrypt_cost = 4
session_timeout = "24h"
max_sessions_per_user = 10
password_min_length = 6
password_require_special = false
password_require_number = false
password_require_uppercase = false

[email]
smtp_host = "${EMAIL_SMTP_HOST:localhost}"
smtp_port = 587
username = "${EMAIL_USERNAME:}"
password = "${EMAIL_PASSWORD:}"
from_address = "${EMAIL_FROM_ADDRESS:noreply@localhost}"
from_name = "${EMAIL_FROM_NAME:Auth Service Local}"

[oauth2]
[oauth2.google]
client_id = "${OAUTH2_GOOGLE_CLIENT_ID:}"
client_secret = "${OAUTH2_GOOGLE_CLIENT_SECRET:}"
redirect_url = "${OAUTH2_GOOGLE_REDIRECT_URL:http://localhost:8001/api/v1/auth/oauth/google/callback}"
enabled = false

[oauth2.github]
client_id = "${OAUTH2_GITHUB_CLIENT_ID:}"
client_secret = "${OAUTH2_GITHUB_CLIENT_SECRET:}"
redirect_url = "${OAUTH2_GITHUB_REDIRECT_URL:http://localhost:8001/api/v1/auth/oauth/github/callback}"
enabled = false

[oauth2.facebook]
client_id = "${OAUTH2_FACEBOOK_CLIENT_ID:}"
client_secret = "${OAUTH2_FACEBOOK_CLIENT_SECRET:}"
redirect_url = "${OAUTH2_FACEBOOK_REDIRECT_URL:http://localhost:8001/api/v1/auth/oauth/facebook/callback}"
enabled = false

[logging]
level = "${LOG_LEVEL:debug}"
format = "${LOG_FORMAT:text}"
output = "${LOG_OUTPUT:stdout}"

[metrics]
enabled = true
path = "${METRICS_PATH:/metrics}"
port = "${METRICS_PORT:8001}"

[tracing]
enabled = false
service_name = "${TRACING_SERVICE_NAME:auth-service-local}"
jaeger_endpoint = "${TRACING_JAEGER_ENDPOINT:http://localhost:14268/api/traces}"
sample_rate = 1.0

[cors]
allowed_origins = ["*"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allowed_headers = ["*"]
exposed_headers = ["X-Total-Count"]
allow_credentials = true
max_age = 3600

[health]
check_interval = "30s"
timeout = "10s"