# =========================================================
# Auth Service Configuration (Production)
# Environment variables will override these values
# =========================================================

[server]
host = "0.0.0.0"
port = "8001"
read_timeout = "30s"
write_timeout = "30s"
idle_timeout = "120s"
shutdown_timeout = "30s"

[database]
host = "postgres-auth"
port = "5432"
name = "auth_db"
user = "postgres"
password = "testpassword"
ssl_mode = "disable"
max_open_conns = 25
max_idle_conns = 10
conn_max_lifetime = "1h"
migration_path = "migrations"

[redis]
url = "redis://redis-cache:6379"
password = ""
db = 0
max_retries = 3
pool_size = 10
min_idle_conns = 2
dial_timeout = "5s"
read_timeout = "3s"
write_timeout = "3s"
pool_timeout = "4s"
idle_timeout = "300s"

[jwt]
access_secret = "production-access-secret-key-minimum-32-characters-long-change-this"
refresh_secret = "production-refresh-secret-key-minimum-32-characters-long-change-this"
issuer = "auth-service"
access_expiry = "15m"
refresh_expiry = "168h"
algorithm = "HS256"

[security]
bcrypt_cost = 12
session_timeout = "24h"
max_sessions_per_user = 5
password_min_length = 8
password_require_special = true
password_require_number = true
password_require_uppercase = true

[email]
smtp_host = "smtp.example.com"
smtp_port = 587
username = ""
password = ""
from_address = "noreply@example.com"
from_name = "Auth Service"


[logging]
level = "info"
format = "json"
output = "stdout"

[metrics]
enabled = true
path = "/metrics"
port = "8001"

[tracing]
enabled = false
service_name = "auth-service"
jaeger_endpoint = "http://jaeger:14268/api/traces"
sample_rate = 0.1

[cors]
allowed_origins = ["http://localhost:3000"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allowed_headers = ["Origin", "Content-Type", "Accept", "Authorization"]
exposed_headers = ["X-Total-Count"]
allow_credentials = true
max_age = 3600

[health]
check_interval = "30s"
timeout = "10s"